#!/usr/bin/env bash
# ──────────────────────────────────────────────────────────────────────
# setup.sh — Automated Pi5 deployment for OpenClaw (hardened)
# ──────────────────────────────────────────────────────────────────────
#
# This script:
#   1. Creates required directories with secure permissions
#   2. Generates a random gateway token
#   3. Writes the .env file
#   4. Copies the hardened config to the state directory
#   5. Starts the Docker container
#   6. Prints next steps (Tailscale Serve, WhatsApp QR)
#
# Usage:
#   sudo ./setup.sh
# ──────────────────────────────────────────────────────────────────────

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# ── Colors ───────────────────────────────────────────────────────────

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

log()  { echo -e "${GREEN}[+]${NC} $*"; }
warn() { echo -e "${YELLOW}[!]${NC} $*"; }
err()  { echo -e "${RED}[x]${NC} $*" >&2; }
info() { echo -e "${CYAN}[i]${NC} $*"; }

# ── Preflight checks ────────────────────────────────────────────────

if [[ $EUID -ne 0 ]]; then
    err "This script must be run as root (sudo)."
    exit 1
fi

if ! command -v docker &>/dev/null; then
    err "Docker is not installed. Install it first: https://docs.docker.com/engine/install/debian/"
    exit 1
fi

if ! docker compose version &>/dev/null; then
    err "Docker Compose v2 is not available. Update Docker."
    exit 1
fi

if ! command -v tailscale &>/dev/null; then
    warn "Tailscale is not installed. You will need it for secure remote access."
fi

# ── Step 1: Create directories ──────────────────────────────────────

log "Creating directories..."

mkdir -p /opt/openclaw/state
mkdir -p /opt/openclaw/workspace
mkdir -p /home/manu/backups/openclaw

# State directory holds auth tokens and config — restrict access
chmod 700 /opt/openclaw/state
chmod 755 /opt/openclaw/workspace

# Ensure the node user (UID 1000) inside the container can write
chown -R 1000:1000 /opt/openclaw/state
chown -R 1000:1000 /opt/openclaw/workspace

log "  /opt/openclaw/state     (700, owned by 1000:1000)"
log "  /opt/openclaw/workspace (755, owned by 1000:1000)"
log "  /home/manu/backups/openclaw"

# ── Step 2: Generate gateway token ──────────────────────────────────

GATEWAY_TOKEN=$(openssl rand -hex 32)
log "Generated gateway token: ${GATEWAY_TOKEN:0:8}...${GATEWAY_TOKEN: -8} (64 chars)"

# ── Step 3: Write .env file ─────────────────────────────────────────

ENV_FILE="$SCRIPT_DIR/.env"

if [[ -f "$ENV_FILE" ]]; then
    warn ".env file already exists. Backing up to .env.bak"
    cp "$ENV_FILE" "${ENV_FILE}.bak"
fi

cat > "$ENV_FILE" <<EOF
# OpenClaw Pi5 Deployment — Generated by setup.sh on $(date '+%Y-%m-%d %H:%M:%S')

GATEWAY_TOKEN=$GATEWAY_TOKEN
OPENCLAW_STATE_DIR=/opt/openclaw/state
OPENCLAW_WORKSPACE_DIR=/opt/openclaw/workspace
OPENCLAW_IMAGE=mqstro/openclaw:hardened

BACKUP_LOCAL_DIR=/home/manu/backups/openclaw
BACKUP_REMOTE_HOST=root@217.154.169.120
BACKUP_REMOTE_DIR=/root/backups/pi5-daily
BACKUP_RETENTION_DAYS=30
EOF

chmod 600 "$ENV_FILE"
log "Wrote $ENV_FILE (permissions: 600)"

# ── Step 4: Copy hardened config ─────────────────────────────────────

CONFIG_SRC="$SCRIPT_DIR/openclaw-hardened.json"
CONFIG_DST="/opt/openclaw/state/openclaw.json"

if [[ ! -f "$CONFIG_SRC" ]]; then
    err "Config file not found: $CONFIG_SRC"
    exit 1
fi

cp "$CONFIG_SRC" "$CONFIG_DST"
chown 1000:1000 "$CONFIG_DST"
chmod 600 "$CONFIG_DST"
log "Copied hardened config to $CONFIG_DST"

# ── Step 5: Copy deployment files to /opt/openclaw ───────────────────

mkdir -p /opt/openclaw/deploy
cp "$SCRIPT_DIR/backup.sh" /opt/openclaw/deploy/
cp "$SCRIPT_DIR/iptables-whitelist.sh" /opt/openclaw/deploy/
chmod +x /opt/openclaw/deploy/backup.sh
chmod +x /opt/openclaw/deploy/iptables-whitelist.sh
log "Copied operational scripts to /opt/openclaw/deploy/"

# ── Step 6: Start Docker container ──────────────────────────────────

log "Starting OpenClaw container..."
cd "$SCRIPT_DIR"
docker compose up -d

# Wait for container to be healthy
info "Waiting for container to start..."
sleep 5

if docker ps --filter "name=openclaw" --filter "status=running" -q | grep -q .; then
    log "Container is running!"
else
    warn "Container may not have started correctly. Check: docker logs openclaw"
fi

# ── Step 7: Print next steps ────────────────────────────────────────

echo ""
echo -e "${CYAN}════════════════════════════════════════════════════════════${NC}"
echo -e "${CYAN}  OpenClaw Hardened Deployment — Setup Complete${NC}"
echo -e "${CYAN}════════════════════════════════════════════════════════════${NC}"
echo ""
echo -e "${GREEN}Gateway Token:${NC} $GATEWAY_TOKEN"
echo -e "${GREEN}Config:${NC}        $CONFIG_DST"
echo -e "${GREEN}State:${NC}         /opt/openclaw/state"
echo -e "${GREEN}Workspace:${NC}     /opt/openclaw/workspace"
echo ""
echo -e "${YELLOW}── Next Steps ──────────────────────────────────────────────${NC}"
echo ""
echo "1. SET UP TAILSCALE SERVE (required for remote access):"
echo ""
echo "   # Expose OpenClaw gateway via Tailscale (HTTPS, auth required)"
echo "   tailscale serve --bg https+insecure://localhost:18789"
echo ""
echo "   # Verify it works:"
echo "   tailscale serve status"
echo ""
echo "2. CONNECT WHATSAPP:"
echo ""
echo "   # View the WhatsApp QR code in container logs:"
echo "   docker logs openclaw 2>&1 | grep -A 20 'QR'"
echo ""
echo "   # Or follow logs live:"
echo "   docker logs -f openclaw"
echo ""
echo "   Scan the QR code with WhatsApp on your phone."
echo ""
echo "3. UPDATE WHATSAPP ALLOWLIST:"
echo ""
echo "   # Edit the config to add your phone number:"
echo "   nano /opt/openclaw/state/openclaw.json"
echo "   # Change: \"+49REPLACE_WITH_YOUR_NUMBER\" -> your actual number"
echo "   # Then restart: docker compose restart"
echo ""
echo "4. APPLY FIREWALL RULES (recommended):"
echo ""
echo "   sudo /opt/openclaw/deploy/iptables-whitelist.sh"
echo ""
echo "5. SET UP DAILY BACKUPS:"
echo ""
echo "   # Add to crontab:"
echo "   sudo crontab -e"
echo "   # Add this line (runs at 3:30 AM, after DB backups):"
echo "   30 3 * * * /opt/openclaw/deploy/backup.sh >> /var/log/openclaw-backup.log 2>&1"
echo ""
echo "6. SET UP FIREWALL REFRESH (recommended):"
echo ""
echo "   # Add to crontab (refreshes DNS-resolved IPs every 6 hours):"
echo "   0 */6 * * * /opt/openclaw/deploy/iptables-whitelist.sh >> /var/log/openclaw-fw.log 2>&1"
echo ""
echo -e "${CYAN}════════════════════════════════════════════════════════════${NC}"
echo ""
